2018-01-02 10:38:35,772 ERROR: Exception on /explore [GET] [in /home/zetdg/Devasoft/devablog/.devablog/lib/python3.5/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/zetdg/Devasoft/devablog/.devablog/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zetdg/Devasoft/devablog/.devablog/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zetdg/Devasoft/devablog/.devablog/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zetdg/Devasoft/devablog/.devablog/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/zetdg/Devasoft/devablog/.devablog/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zetdg/Devasoft/devablog/.devablog/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zetdg/Devasoft/devablog/.devablog/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/zetdg/Devasoft/devablog/app/routes.py", line 270, in explore
    prev_url=prev_url)
  File "/home/zetdg/Devasoft/devablog/.devablog/lib/python3.5/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/zetdg/Devasoft/devablog/.devablog/lib/python3.5/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/zetdg/Devasoft/devablog/.devablog/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/zetdg/Devasoft/devablog/.devablog/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zetdg/Devasoft/devablog/.devablog/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/zetdg/Devasoft/devablog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/zetdg/Devasoft/devablog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/zetdg/Devasoft/devablog/.devablog/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/zetdg/Devasoft/devablog/.devablog/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/zetdg/Devasoft/devablog/.devablog/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/zetdg/Devasoft/devablog/.devablog/lib/python3.5/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/zetdg/Devasoft/devablog/app/templates/base.html", line 54, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/zetdg/Devasoft/devablog/app/templates/index.html", line 5, in block "app_content"
    <h1>{{_("Hi, %(username)s!",current_user.username) }}</h1>
  File "/home/zetdg/Devasoft/devablog/.devablog/lib/python3.5/site-packages/jinja2/ext.py", line 134, in _gettext_alias
    return __context.call(__context.resolve('gettext'), *args, **kwargs)
TypeError: gettext() takes 2 positional arguments but 3 were given
2018-01-02 10:39:32,006 INFO: Devablog startup [in /home/zetdg/Devasoft/devablog/app/__init__.py:68]
2018-01-02 12:13:51,133 INFO: Devablog startup [in /home/zetdg/Devasoft/devablog/app/__init__.py:68]
2018-01-02 12:13:57,437 INFO: Devablog startup [in /home/zetdg/Devasoft/devablog/app/__init__.py:68]
2018-01-02 12:20:37,221 INFO: Devablog startup [in /home/zetdg/Devasoft/devablog/app/__init__.py:68]
2018-01-02 12:20:44,445 INFO: Devablog startup [in /home/zetdg/Devasoft/devablog/app/__init__.py:68]
2018-01-02 12:20:47,788 INFO: Devablog startup [in /home/zetdg/Devasoft/devablog/app/__init__.py:68]
2018-01-02 12:20:50,273 INFO: Devablog startup [in /home/zetdg/Devasoft/devablog/app/__init__.py:68]
2018-01-02 12:22:04,235 INFO: Devablog startup [in /home/zetdg/Devasoft/devablog/app/__init__.py:68]
2018-01-02 12:22:13,275 INFO: Devablog startup [in /home/zetdg/Devasoft/devablog/app/__init__.py:68]
2018-01-02 12:22:18,186 INFO: Devablog startup [in /home/zetdg/Devasoft/devablog/app/__init__.py:68]
2018-01-02 12:22:52,500 INFO: Devablog startup [in /home/zetdg/Devasoft/devablog/app/__init__.py:68]
2018-01-02 12:23:08,876 INFO: Devablog startup [in /home/zetdg/Devasoft/devablog/app/__init__.py:68]
2018-01-02 12:23:55,046 INFO: Devablog startup [in /home/zetdg/Devasoft/devablog/app/__init__.py:68]
2018-01-02 12:24:12,249 INFO: Devablog startup [in /home/zetdg/Devasoft/devablog/app/__init__.py:68]
2018-01-02 12:24:17,240 INFO: Devablog startup [in /home/zetdg/Devasoft/devablog/app/__init__.py:68]
2018-01-02 12:24:58,835 INFO: Devablog startup [in /home/zetdg/Devasoft/devablog/app/__init__.py:68]
2018-01-02 12:25:04,222 INFO: Devablog startup [in /home/zetdg/Devasoft/devablog/app/__init__.py:68]
2018-01-02 12:25:14,692 INFO: Devablog startup [in /home/zetdg/Devasoft/devablog/app/__init__.py:68]
2018-01-02 12:26:19,177 INFO: Devablog startup [in /home/zetdg/Devasoft/devablog/app/__init__.py:66]
